In [1]:
import numpy as np

arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [4]:
A = np.random.randn(10)
A

array([ 0.96979749,  0.70516762,  0.77876787,  0.33630062, -0.37901188,
        0.29702814, -0.27800707, -0.78070192, -0.71538007,  1.00457193])

In [5]:
B = np.random.randn(10)
B

array([-1.43830516,  1.5191074 ,  1.41295555,  0.16269864, -1.93381296,
       -0.45610364,  1.03221152, -0.29483622,  0.80017622, -0.21340105])

In [6]:
# binary functions

np.add(A,B)

array([-0.46850767,  2.22427502,  2.19172342,  0.49899925, -2.31282484,
       -0.1590755 ,  0.75420444, -1.07553814,  0.08479615,  0.79117088])

In [7]:
np.maximum(A,B)

array([ 0.96979749,  1.5191074 ,  1.41295555,  0.33630062, -0.37901188,
        0.29702814,  1.03221152, -0.29483622,  0.80017622,  1.00457193])

In [8]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-unfuncs'
import webbrowser

In [9]:
webbrowser.open(website)

True